spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        globally_quoted_identifiers: true
  datasource:
    url: 'jdbc:mysql://${DB_URL}:${DB_PORT}/${DB_NAME}?createDatabaseIfNotExist=true'
    username: '${DB_USER}'
    password: '${DB_PASS}'
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
  sql:
    init:
      mode: always
      continue-on-error: true
  mvc:
    format:
      date-time: iso
      date: iso
  mail:
    host: ${MAIL_HOST:sandbox.smtp.mailtrap.io}
    port: ${MAIL_PORT:2525}
    username: ${MAIL_USER}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
server:
  servlet:
    context-path: /api/v1
app:
  reset-password-url: ${REACT_APP_API_URL:http://localhost:8080}/api/v1/auth/create-password
  cache-expiration-minutes: 15
