spring:
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: 'jdbc:mysql://${DB_URL}:${DB_PORT}/${DB_NAME}'
    username: '${DB_USER}'
    password: '${DB_PASS}'
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
  mail:
    host: '${MAIL_HOST}'
    username: '${MAIL_USER}'
    protocol: smtp
    password: '${MAIL_PASSWORD}'
    port: '${MAIL_PORT}'
app:
  url: '${REACT_APP_API_URL}'
email:
  from: '${MAIL_FROM}'
  personal: '${MAIL_PERSONAL}'
